### ISSUE TITLE
Allowing SHA-256?

### ISSUE THREAD

**Issue by sgarbesi** [felthy/grunt-cachebuster#4]
Would be nice to be able to specify the encryption method.

**Comment by lstrojny** [comment]
:+1:

**Comment by felthy** [comment]
Sorry for the lag, I thought I'd already responded to this. Can you give me a use case? It's just that this plugin isn't meant to be about security, the hash just needs to be fast and moderately collision-resistant to help you use long cache timeouts on static(ish) assets - so I'm not sure why you'd care to change the hash algorithm.

**Comment by lstrojny** [comment]
The use case is that you probably want to ban certain hash functions in your project because what isn't security relevant today, can easily become security relevant by changing the use case. I am not saying that’s super realistic but at least I would change to a future proff default and go with any SHA2 function.

**Comment by sgarbesi** [comment]
@felthy exactly what @lstrojny said.

**Comment by felthy** [comment]
OK, thanks, I can't argue with that logic can I? It's not a feature I need for myself though so please feel free to submit a pull request (including a test for the new feature) and I'll be happy to merge it in.

**Comment by lstrojny** [comment]
@felthy can you check the PR?
